### PR TITLE
remove custom fonts from desktop_panels

### PR DESCRIPTION
**Pull request by bmos**

### CODE REVIEW

**Comment by bmos** [comment]
I haven't tested this yet

**Comment by bmos** [comment]
suggested change by https://www.fantasygrounds.com/forums/showthread.php?30856-Combat-Timer-Extension-(v-0-0-1)&p=613576&viewfull=1#post613576

**Comment by Morturg** [comment]
makes sense, there were files that were not used

**Comment by bmos** [comment]
I have now tested this and it works as intended

**Pull request merged**
